# fly.toml app configuration file generated for homeslice on 2024-04-17T14:49:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'homeslice'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 5050
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  HOST = "0.0.0.0"
  NODE_ENV = "production"